### ISSUE TITLE
Question RD?

### ISSUE THREAD

**Issue by interludic** [diegobanos/php-glicko2#2]
"Whenever the value of RD is calculated greater than 350, then it must be set to 350 (RD = 350)"

I cannot see a mention of 350 being restricted in the code?

ref: https://www.englishchess.org.uk/wp-content/uploads/2012/04/The_Glicko_system_for_beginners1.pdf

**Comment by diegobanos** [comment]
I think that the 350 maximum you are talking about only applies to the Glicko system, but not to the Glicko-2 system. This project is an implementation of the latter. You can look at the formulas I implemented in the PDF that's included in README.md
